#ifndef __RESONITE_RESONITE_SERIALIZATION_H__
#define __RESONITE_RESONITE_SERIALIZATION_H__

#include <cstdint.h>

#include "py/obj.h"
#include "py/runtime.h"
#include "resonite_api_types.h"

// This must match SimpleSerialization.SimpleType in SimpleSerialization.cs
typedef enum {
    RESONITE_SERIALIZATION_TYPE_UNKNOWN = 0,
    RESONITE_SERIALIZATION_TYPE_BOOL = 1,
    RESONITE_SERIALIZATION_TYPE_BOOL2 = 2,
    RESONITE_SERIALIZATION_TYPE_BOOL3 = 3,
    RESONITE_SERIALIZATION_TYPE_BOOL4 = 4,
    RESONITE_SERIALIZATION_TYPE_INT = 5,
    RESONITE_SERIALIZATION_TYPE_INT2 = 6,
    RESONITE_SERIALIZATION_TYPE_INT3 = 7,
    RESONITE_SERIALIZATION_TYPE_INT4 = 8,
    RESONITE_SERIALIZATION_TYPE_UINT = 9,
    RESONITE_SERIALIZATION_TYPE_UINT2 = 10,
    RESONITE_SERIALIZATION_TYPE_UINT3 = 11,
    RESONITE_SERIALIZATION_TYPE_UINT4 = 12,
    RESONITE_SERIALIZATION_TYPE_LONG = 13,
    RESONITE_SERIALIZATION_TYPE_LONG2 = 14,
    RESONITE_SERIALIZATION_TYPE_LONG3 = 15,
    RESONITE_SERIALIZATION_TYPE_LONG4 = 16,
    RESONITE_SERIALIZATION_TYPE_ULONG = 17,
    RESONITE_SERIALIZATION_TYPE_ULONG2 = 18,
    RESONITE_SERIALIZATION_TYPE_ULONG3 = 19,
    RESONITE_SERIALIZATION_TYPE_ULONG4 = 20,
    RESONITE_SERIALIZATION_TYPE_FLOAT = 21,
    RESONITE_SERIALIZATION_TYPE_FLOAT2 = 22,
    RESONITE_SERIALIZATION_TYPE_FLOAT3 = 23,
    RESONITE_SERIALIZATION_TYPE_FLOAT4 = 24,
    RESONITE_SERIALIZATION_TYPE_FLOATQ = 25,
    RESONITE_SERIALIZATION_TYPE_DOUBLE = 26,
    RESONITE_SERIALIZATION_TYPE_DOUBLE2 = 27,
    RESONITE_SERIALIZATION_TYPE_DOUBLE3 = 28,
    RESONITE_SERIALIZATION_TYPE_DOUBLE4 = 29,
    RESONITE_SERIALIZATION_TYPE_DOUBLEQ = 30,
    RESONITE_SERIALIZATION_TYPE_STRING = 31,
    RESONITE_SERIALIZATION_TYPE_COLOR = 32,
    RESONITE_SERIALIZATION_TYPE_COLORX = 33,
    RESONITE_SERIALIZATION_TYPE_REF_ID = 34,
    RESONITE_SERIALIZATION_TYPE_SLOT = 35,
    RESONITE_SERIALIZATION_TYPE_USER = 36,
    RESONITE_SERIALIZATION_TYPE_USER_ROOT = 37,
} resonite_serialization_type_t;

// Deserializes a serialized SimpleType.
//
// Bool -> bool
// Bool2, 3, 4 -> tuple of bools
// Int, Uint, Long, ULong -> int
// Int2, 3, 4, etc -> tuple of ints
// Float, Double -> float
// Float2, 3, 4, etc -> tuple of floats
// String -> str
// Slot -> Slot
// User -> User
// UserRoot -> UserRoot
// RefID -> RefID
extern mp_obj_t resonite_deserialize(uint8_t* data);

#endif // __RESONITE_RESONITE_SERIALIZATION_H__
