
#include "mp_resonite_api.h"

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "py/obj.h"
#include "py/runtime.h"
#include "resonite_api.h"
#include "mp_resonite_utils.h"

// Micropython shims for the Resonite API.
// Autogenerated by generate_api.py. DO NOT EDIT.

mp_obj_t resonite__slot__root_slot() {
  resonite_refid_t outSlot;

  resonite_error_t _err = slot__root_slot(
    &outSlot);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outSlot)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__get_parent(mp_obj_t slot) {
  resonite_refid_t outParent;

  resonite_error_t _err = slot__get_parent(
    mp_obj_int_get_uint64_checked(slot), 
    &outParent);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outParent)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__get_active_user(mp_obj_t slot) {
  resonite_refid_t outUser;

  resonite_error_t _err = slot__get_active_user(
    mp_obj_int_get_uint64_checked(slot), 
    &outUser);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outUser)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__get_active_user_root(mp_obj_t slot) {
  resonite_refid_t outUserRoot;

  resonite_error_t _err = slot__get_active_user_root(
    mp_obj_int_get_uint64_checked(slot), 
    &outUserRoot);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outUserRoot)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__get_object_root(mp_obj_t slot, mp_obj_t only_explicit) {
  resonite_refid_t outObjectRoot;

  resonite_error_t _err = slot__get_object_root(
    mp_obj_int_get_uint64_checked(slot), 
    mp_obj_is_true(only_explicit) ? 1 : 0, 
    &outObjectRoot);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outObjectRoot)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__get_name(mp_obj_t slot) {
  char * outName;

  resonite_error_t _err = slot__get_name(
    mp_obj_int_get_uint64_checked(slot), 
    &outName);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_null_terminated_str(outName)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__set_name(mp_obj_t slot, mp_obj_t name) {

  resonite_error_t _err = slot__set_name(
    mp_obj_int_get_uint64_checked(slot), 
    mp_obj_str_get_str(name));
  mp_obj_t _outs[1] = {
    mp_obj_new_int_from_ll(_err)};


  return mp_obj_new_tuple(1, _outs);
}

mp_obj_t resonite__slot__get_num_children(mp_obj_t slot) {
  int32_t outNumChildren;

  resonite_error_t _err = slot__get_num_children(
    mp_obj_int_get_uint64_checked(slot), 
    &outNumChildren);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outNumChildren)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__get_child(mp_obj_t slot, mp_obj_t index) {
  resonite_refid_t outChild;

  resonite_error_t _err = slot__get_child(
    mp_obj_int_get_uint64_checked(slot), 
    (int32_t)mp_obj_get_int(index), 
    &outChild);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outChild)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__find_child_by_name(mp_obj_t slot, mp_obj_t name, mp_obj_t match_substring, mp_obj_t ignore_case, mp_obj_t max_depth) {
  resonite_refid_t outChild;

  resonite_error_t _err = slot__find_child_by_name(
    mp_obj_int_get_uint64_checked(slot), 
    mp_obj_str_get_str(name), 
    mp_obj_is_true(match_substring) ? 1 : 0, 
    mp_obj_is_true(ignore_case) ? 1 : 0, 
    (int32_t)mp_obj_get_int(max_depth), 
    &outChild);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outChild)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__find_child_by_tag(mp_obj_t slot, mp_obj_t tag, mp_obj_t max_depth) {
  resonite_refid_t outChild;

  resonite_error_t _err = slot__find_child_by_tag(
    mp_obj_int_get_uint64_checked(slot), 
    mp_obj_str_get_str(tag), 
    (int32_t)mp_obj_get_int(max_depth), 
    &outChild);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outChild)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__get_component(mp_obj_t slot, mp_obj_t typeNamePtr) {
  resonite_refid_t outComponentIdPtr;

  resonite_error_t _err = slot__get_component(
    mp_obj_int_get_uint64_checked(slot), 
    mp_obj_str_get_str(typeNamePtr), 
    &outComponentIdPtr);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outComponentIdPtr)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__slot__get_components(mp_obj_t slot) {
  int32_t outComponentListLength;
  resonite_refid_t* outComponentListData;

  resonite_error_t _err = slot__get_components(
    mp_obj_int_get_uint64_checked(slot), 
    &outComponentListLength, 
    &outComponentListData);
  mp_obj_t _outs[3] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outComponentListLength), 
    mp_obj_new_int_from_ll(outComponentListData)};

  free(outComponentListData);

  return mp_obj_new_tuple(3, _outs);
}

mp_obj_t resonite__component__get_type_name(mp_obj_t component) {
  char * outPtr;

  resonite_error_t _err = component__get_type_name(
    mp_obj_int_get_uint64_checked(component), 
    &outPtr);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_null_terminated_str(outPtr)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__component__get_member(mp_obj_t componentRefId, mp_obj_t namePtr) {
  resonite_type_t outTypePtr;
  uint64_t outRefIdPtr;

  resonite_error_t _err = component__get_member(
    mp_obj_int_get_uint64_checked(componentRefId), 
    mp_obj_str_get_str(namePtr), 
    &outTypePtr, 
    &outRefIdPtr);
  mp_obj_t _outs[3] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outTypePtr), 
    mp_obj_new_int_from_ll(outRefIdPtr)};


  return mp_obj_new_tuple(3, _outs);
}

mp_obj_t resonite__value__get_int(mp_obj_t refId) {
  int32_t outPtr;

  resonite_error_t _err = value__get_int(
    mp_obj_int_get_uint64_checked(refId), 
    &outPtr);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_int_from_ll(outPtr)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__value__get_float(mp_obj_t refId) {
  float outPtr;

  resonite_error_t _err = value__get_float(
    mp_obj_int_get_uint64_checked(refId), 
    &outPtr);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_float(outPtr)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__value__get_double(mp_obj_t refId) {
  double outPtr;

  resonite_error_t _err = value__get_double(
    mp_obj_int_get_uint64_checked(refId), 
    &outPtr);
  mp_obj_t _outs[2] = {
    mp_obj_new_int_from_ll(_err), 
    mp_obj_new_float(outPtr)};


  return mp_obj_new_tuple(2, _outs);
}

mp_obj_t resonite__value__set_int(mp_obj_t refId, mp_obj_t inPtr) {

  resonite_error_t _err = value__set_int(
    mp_obj_int_get_uint64_checked(refId), 
    (int32_t)mp_obj_get_int(inPtr));
  mp_obj_t _outs[1] = {
    mp_obj_new_int_from_ll(_err)};


  return mp_obj_new_tuple(1, _outs);
}

mp_obj_t resonite__value__set_float(mp_obj_t refId, mp_obj_t inPtr) {

  resonite_error_t _err = value__set_float(
    mp_obj_int_get_uint64_checked(refId), 
    (int32_t)mp_obj_get_int(inPtr));
  mp_obj_t _outs[1] = {
    mp_obj_new_int_from_ll(_err)};


  return mp_obj_new_tuple(1, _outs);
}

mp_obj_t resonite__value__set_double(mp_obj_t refId, mp_obj_t inPtr) {

  resonite_error_t _err = value__set_double(
    mp_obj_int_get_uint64_checked(refId), 
    (int32_t)mp_obj_get_int(inPtr));
  mp_obj_t _outs[1] = {
    mp_obj_new_int_from_ll(_err)};


  return mp_obj_new_tuple(1, _outs);
}

