
#ifndef __DERGWASM_MICROPYTHON_USERCMODULE_RESONITE_RESONITE_API_H__
#define __DERGWASM_MICROPYTHON_USERCMODULE_RESONITE_RESONITE_API_H__

#include "py/obj.h"
#include "py/runtime.h"

// Micropython shims for the Resonite API.
// Autogenerated by generate_api.py. DO NOT EDIT.

extern mp_obj_t resonite__slot__root_slot();
extern mp_obj_t resonite__slot__get_parent(mp_obj_t slot);
extern mp_obj_t resonite__slot__get_active_user(mp_obj_t slot);
extern mp_obj_t resonite__slot__get_active_user_root(mp_obj_t slot);
extern mp_obj_t resonite__slot__get_object_root(mp_obj_t slot, mp_obj_t only_explicit);
extern mp_obj_t resonite__slot__get_name(mp_obj_t slot);
extern mp_obj_t resonite__slot__set_name(mp_obj_t slot, mp_obj_t name);
extern mp_obj_t resonite__slot__get_num_children(mp_obj_t slot);
extern mp_obj_t resonite__slot__get_child(mp_obj_t slot, mp_obj_t index);
extern mp_obj_t resonite__slot__get_children(mp_obj_t slot);
extern mp_obj_t resonite__slot__find_child_by_name(size_t n_args, const mp_obj_t *args);
extern mp_obj_t resonite__slot__find_child_by_tag(mp_obj_t slot, mp_obj_t tag, mp_obj_t max_depth);
extern mp_obj_t resonite__slot__get_component(mp_obj_t slot, mp_obj_t typeName);
extern mp_obj_t resonite__slot__get_components(mp_obj_t slot);
extern mp_obj_t resonite__component__get_type_name(mp_obj_t component);
extern mp_obj_t resonite__component__get_member(mp_obj_t component, mp_obj_t name);
extern mp_obj_t resonite__value__get_int(mp_obj_t refId);
extern mp_obj_t resonite__value__get_float(mp_obj_t refId);
extern mp_obj_t resonite__value__get_double(mp_obj_t refId);
extern mp_obj_t resonite__value__set_int(mp_obj_t refId, mp_obj_t value);
extern mp_obj_t resonite__value__set_float(mp_obj_t refId, mp_obj_t value);
extern mp_obj_t resonite__value__set_double(mp_obj_t refId, mp_obj_t value);

#endif // __DERGWASM_MICROPYTHON_USERCMODULE_RESONITE_RESONITE_API_H__
