
#ifndef __DERGWASM_C_RESONITE_API_H__
#define __DERGWASM_C_RESONITE_API_H__

#include <stdbool.h>
#include <stdint.h>

#include "resonite_api_types.h"

// C API corresponding to the Resonite API.
// Autogenerated by generate_api.py. DO NOT EDIT.

extern resonite_refid_t slot__root_slot();
extern resonite_refid_t slot__get_parent(
    resonite_refid_t slot);
extern resonite_refid_t slot__get_active_user(
    resonite_refid_t slot);
extern resonite_refid_t slot__get_active_user_root(
    resonite_refid_t slot);
extern resonite_refid_t slot__get_object_root(
    resonite_refid_t slot, 
    bool only_explicit);
extern char * slot__get_name(
    resonite_refid_t slot);
extern void slot__set_name(
    resonite_refid_t slot, 
    char * name);
extern int32_t slot__get_num_children(
    resonite_refid_t slot);
extern resonite_refid_t slot__get_child(
    resonite_refid_t slot, 
    int32_t index);
extern resonite_refid_t slot__find_child_by_name(
    resonite_refid_t slot, 
    char * namePtr, 
    bool match_substring, 
    bool ignore_case, 
    int32_t max_depth);
extern resonite_refid_t slot__find_child_by_tag(
    resonite_refid_t slot, 
    char * tagPtr, 
    int32_t max_depth);
extern resonite_refid_t slot__get_component(
    resonite_refid_t slot, 
    char * typeNamePtr);
extern char * component__get_type_name(
    resonite_refid_t component_id);
extern int32_t component__get_member(
    resonite_refid_t componentRefId, 
    char * namePtr, 
    void * outTypePtr, 
    void * outRefIdPtr);
extern int32_t value__get_int(
    resonite_refid_t refId, 
    void * outPtr);
extern int32_t value__get_float(
    resonite_refid_t refId, 
    void * outPtr);
extern int32_t value__get_double(
    resonite_refid_t refId, 
    void * outPtr);
extern int32_t value__set_int(
    resonite_refid_t refId, 
    void * inPtr);
extern int32_t value__set_float(
    resonite_refid_t refId, 
    void * inPtr);
extern int32_t value__set_double(
    resonite_refid_t refId, 
    void * inPtr);

#endif // __DERGWASM_C_RESONITE_API_H__
